### PR TITLE
fix: get remote branches correctly when there are multiple origins

### LINKED ISSUE #972: Setup wizard showing incomplete branch names
**Describe the bug**
After run `npx shipjs setup`, the "What is your base branch?" prompt appears but the options to select are displaying branch names not complete, but seeming to be trimmed of several leading letters.

**To Reproduce**
1. Run `npx shipjs setup`

**Expected behavior**
Showing complete branch names

**Screenshots**
image

**Environment (please complete the following information):**
 - environment: (your local machine, CircleCI, Travis CI, etc.)
 - `node -v`: v14.18.1
 - `npm -v` or `yarn -v`: npm 6.14.15
- Ship.js version: 0.24.2 (via npx)

**Additional context:**
I have multiple origins configured. Looks like it's the possible cause.
https://github.com/algolia/shipjs/blob/main/packages/shipjs-lib/src/lib/git/getRemoteBranches.js#L14

### PR DESCRIPTION
**Pull request by eunjae-lee**
## Summary

This PR fixes `getRemoteBranches` function to get remote branches correctly when there are multiple origins.

fixes #972

### CODE REVIEW

File: packages/shipjs-lib/src/lib/git/getRemoteBranches.js [hunk 1]
```diff
@@ -11,13 +11,19 @@ $ git branch -r
...
     .toString()
     .trim()
     .split('\n')
     .map((line) => line.trim())
-    .filter(Boolean)
     .filter((line) => !line.includes(' -> '))
-    .map((line) => line.slice(remote.length + 1));
+    .map((line) => {
+      const origin = origins.find((_origin) => line.startsWith(`${_origin}/`));
+      return origin ? line.slice(origin.length + 1) : null;
```
Comment (Haroenv) [inline packages/shipjs-lib/src/lib/git/getRemoteBranches.js:26]: origin can't really be undefined, maybe it makes more sense for an error (can't read slice of undefined) than dealing with `null` as a possible output. What do you think?

**Review by Haroenv — APPROVED** [review]
can be simplified a little, as origin can't be something unknown

File: packages/shipjs-lib/src/lib/git/getRemoteBranches.js (hunk 1 above)
Comment (eunjae-lee) [reply packages/shipjs-lib/src/lib/git/getRemoteBranches.js]: Yeah, thinking about it again, it makes sense origins and branch names are synchronised in a way that `origin` variable must be truthy.

**Review by Haroenv — APPROVED** [review]
