### PR TITLE
fix(chore): warn appropriately on supplying invalid flags

### LINKED ISSUE #379: Handle the errors thrown while supplying invalid flags
```bash
$ shipjs prepare --h
Error: Unknown or unexpected option: --h
    at arg (/home/james-the-hacker/CodeSpace/GitHub-Projects/shipjs/packages/shipjs/node_modules/arg/index.js:88:19)
    at Proxy.cli (/home/james-the-hacker/CodeSpace/GitHub-Projects/shipjs/packages/shipjs/src/cli.js:55:7)
    at /home/james-the-hacker/CodeSpace/GitHub-Projects/shipjs/packages/shipjs/bin/shipjs:6:33
    at Object.<anonymous> (/home/james-the-hacker/CodeSpace/GitHub-Projects/shipjs/packages/shipjs/bin/shipjs:11:3)
    at Module._compile (internal/modules/cjs/loader.js:868:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:879:10)
    at Module.load (internal/modules/cjs/loader.js:731:32)
    at Function.Module._load (internal/modules/cjs/loader.js:644:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:931:10)
    at internal/main/run_main_module.js:17:11 {
  code: 'ARG_UNKNOWN_OPTION'
}
```

### PR DESCRIPTION
**Pull request by jamesgeorge007**
closes #379

### CODE REVIEW

File: packages/shipjs/src/cli.js [hunk 1]
```diff
@@ -50,8 +50,12 @@ export async function cli(argv) {
...
-    parseArgs(argSpec, { permissive: false, argv })
-  );
-  await fn(opts);
+  try {
+    const opts = removeDoubleDash(
+      parseArgs(argSpec, { permissive: false, argv })
+    );
+    await fn(opts);
+  } catch (err) {
+  	console.log('' + err);
```
Comment (Haroenv) [inline packages/shipjs/src/cli.js]: We should rather only console.log when `error.code === 'ARG_UNKNOWN_OPTION'`, and throw in other cases I think

Comment (eunjae-lee) [reply packages/shipjs/src/cli.js]: @jamesgeorge007 I agree with Haroen.
Can you specifically console.log when error code is that, and otherwise just throw it as is?

**Comment by jamesgeorge007** [comment]
@eunjae-lee hope we're good to go.

**Comment by eunjae-lee** [comment]
@jamesgeorge007 congrats 🎉 
Thanks for your contribution.
If you want yourself on the contributors list, 
you can simply create a PR for that.
You can update the list by running the following command:
```
yarn contributors:add jamesgeorge007 code
```

**Comment by jamesgeorge007** [comment]
#387
